FROM node:16-alpine
WORKDIR /app

ARG GOOGLE_CLIENT_ID
ENV REACT_APP_GOOGLE_CLIENT_ID $GOOGLE_CLIENT_ID

COPY ./package.json .
COPY ./yarn.lock .
COPY ./tsconfig.json .
RUN yarn

CMD ["yarn", "start"]